[Unit]
Wants=docker.service
After=docker.service

[Service]
ExecStartPre=/bin/sh -c 'i=0; while [ "$i" -lt 60 ]; do /usr/sbin/ip -4 addr show dev docker0 2>/dev/null | /usr/bin/grep -q "inet 172.17.0.1/" && exit 0; i=$((i+1)); /usr/bin/sleep 1; done; exit 1'
